# Generated by Django 5.2.3 on 2025-06-29 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
