# Generated by Django 5.2.3 on 2025-06-29 07:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_users_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="users",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="users",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("seller", "Seller"),
                    ("customer", "Customer"),
                ],
                default="customer",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="users",
            name="verification_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="users",
            name="wallet",
            field=models.IntegerField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name="users",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="users",
            name="phone_number",
            field=models.CharField(default="0000000000", max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
